//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scripts/Editor/Cheats/EditorControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace Unity3D.Editor.Cheats
{
    public partial class @EditorControls: IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @EditorControls()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""EditorControls"",
    ""maps"": [
        {
            ""name"": ""Cheats"",
            ""id"": ""cb0a6a51-d43f-42b4-903d-54e9cd1fb1a4"",
            ""actions"": [
                {
                    ""name"": ""NextTurn"",
                    ""type"": ""Button"",
                    ""id"": ""3bd1a429-38ac-4c2f-9979-dd2cdf94fb53"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Kill"",
                    ""type"": ""Button"",
                    ""id"": ""1b78fd7d-0a94-4636-89cf-db567520e11a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""46df12a2-ae49-4664-b885-695cfae888fa"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NextTurn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""84fcc5e4-7dae-4fb3-9cd6-3f16b58c3d84"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Kill"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // Cheats
            m_Cheats = asset.FindActionMap("Cheats", throwIfNotFound: true);
            m_Cheats_NextTurn = m_Cheats.FindAction("NextTurn", throwIfNotFound: true);
            m_Cheats_Kill = m_Cheats.FindAction("Kill", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }

        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }

        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // Cheats
        private readonly InputActionMap m_Cheats;
        private List<ICheatsActions> m_CheatsActionsCallbackInterfaces = new List<ICheatsActions>();
        private readonly InputAction m_Cheats_NextTurn;
        private readonly InputAction m_Cheats_Kill;
        public struct CheatsActions
        {
            private @EditorControls m_Wrapper;
            public CheatsActions(@EditorControls wrapper) { m_Wrapper = wrapper; }
            public InputAction @NextTurn => m_Wrapper.m_Cheats_NextTurn;
            public InputAction @Kill => m_Wrapper.m_Cheats_Kill;
            public InputActionMap Get() { return m_Wrapper.m_Cheats; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(CheatsActions set) { return set.Get(); }
            public void AddCallbacks(ICheatsActions instance)
            {
                if (instance == null || m_Wrapper.m_CheatsActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_CheatsActionsCallbackInterfaces.Add(instance);
                @NextTurn.started += instance.OnNextTurn;
                @NextTurn.performed += instance.OnNextTurn;
                @NextTurn.canceled += instance.OnNextTurn;
                @Kill.started += instance.OnKill;
                @Kill.performed += instance.OnKill;
                @Kill.canceled += instance.OnKill;
            }

            private void UnregisterCallbacks(ICheatsActions instance)
            {
                @NextTurn.started -= instance.OnNextTurn;
                @NextTurn.performed -= instance.OnNextTurn;
                @NextTurn.canceled -= instance.OnNextTurn;
                @Kill.started -= instance.OnKill;
                @Kill.performed -= instance.OnKill;
                @Kill.canceled -= instance.OnKill;
            }

            public void RemoveCallbacks(ICheatsActions instance)
            {
                if (m_Wrapper.m_CheatsActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(ICheatsActions instance)
            {
                foreach (var item in m_Wrapper.m_CheatsActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_CheatsActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public CheatsActions @Cheats => new CheatsActions(this);
        public interface ICheatsActions
        {
            void OnNextTurn(InputAction.CallbackContext context);
            void OnKill(InputAction.CallbackContext context);
        }
    }
}
